name: CI

on:
  push:
    branches:
      - "develop"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          [ -f ./yarn.lock ] && yarn || npm i

      - name: Generate Docs
        run: npm run docs

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: 'docs: pixel-art'
          file_pattern: docs/*
          commit_user_name: divlook
          commit_user_email: uihyeon.cha@gmail.com
          push_options: '--force'

  release:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-user-name: divlook
          git-user-email: uihyeon.cha@gmail.com

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
